config/routes.rb
Railsgirls1::Application.routes.draw do

  

  

  resources :quotes

  resources :memberimages

	devise_for :members,:controllers => { :registrations =>'registration'}
	match 'dashboard' => 'home#dashboard'

	resources :comments

	root :to => redirect('/ideas')

	resources :ideas
	match '/contact', :to => 'static#contact'
	match '/technonews', :to => 'static#techno_news'
	match '/socialnews', :to => 'static#social_news'
	match '/kushii', :to => 'static#kushi'
	match '/profile', :to => 'static#profile'
	match '/memberslist', :to => 'static#memberslist'
  match '/details' => 'static#details'
	
	get 'ideas/poll'
	post 'ideas/poll'
	resources :kushis

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :idea_id, :user_name
  validates :body, :presence => true
  belongs_to :idea
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :signin_check, :only => ["create"]
before_filter :admin_check, :only => ["index","show","edit","update","destroy"]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
	@idea= Idea.find(params[:comment][:idea_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @idea, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
  private
  
  def signin_check
  if !member_signed_in?
  redirect_to new_member_session_path
  end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<body ng-app="">
<div ng-show="userComment" >
<div class="hero-unit-comments">
<pre style="background-color:#BCC9C9"><code><p>{{userComment}}</p></code></pre>
</div>
</div>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <% if member_signed_in? %>
  <div class="field">
    
    <%= f.hidden_field :user_name, :value => current_member.username %>
  </div>
  <% end %>
  <div class="field">
    <b>Share your comment..!!</b><%= image_tag "comments.png", size: "40x20" %><br/>
    <%= f.text_area :body, :size=> "440x6", "ng-model" => "userComment" %>
  </div>
  <div class="field">
    <%= f.hidden_field :idea_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</body>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Body</th>
    <th>Idea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.idea_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User name:</b>
  <%= @comment.user_name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Idea:</b>
  <%= @comment.idea_id %>
</p>


<!-- <%= link_to 'Edit', edit_comment_path(@comment) %> | -->
<!--<%= link_to 'Back', comments_path %> -->