config/routes.rb
Railsgirls1::Application.routes.draw do

  

  

  resources :quotes

  resources :memberimages

	devise_for :members,:controllers => { :registrations =>'registration'}
	match 'dashboard' => 'home#dashboard'

	resources :comments

	root :to => redirect('/ideas')

	resources :ideas
	match '/contact', :to => 'static#contact'
	match '/technonews', :to => 'static#techno_news'
	match '/socialnews', :to => 'static#social_news'
	match '/kushii', :to => 'static#kushi'
	match '/profile', :to => 'static#profile'
	match '/memberslist', :to => 'static#memberslist'
  match '/details' => 'static#details'
	
	get 'ideas/poll'
	post 'ideas/poll'
	resources :kushis

end

app/models/memberimage.rb
class Memberimage < ActiveRecord::Base
mount_uploader :image, ImageUploader
  attr_accessible :image, :member_id
  validates :member_id, :uniqueness => true
  validates :image, :presence => true
  belongs_to :member
end

app/controllers/memberimages_controller.rb
class MemberimagesController < ApplicationController
  # GET /memberimages
  # GET /memberimages.json
  def index
    @memberimages = Memberimage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberimages }
    end
  end

  # GET /memberimages/1
  # GET /memberimages/1.json
  def show
    @memberimage = Memberimage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memberimage }
    end
  end

  # GET /memberimages/new
  # GET /memberimages/new.json
  def new
    @memberimage = Memberimage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memberimage }
    end
  end

  # GET /memberimages/1/edit
  def edit
    @memberimage = Memberimage.find(params[:id])
  end

  # POST /memberimages
  # POST /memberimages.json
  def create
    @memberimage = Memberimage.new(params[:memberimage])

    respond_to do |format|
      if @memberimage.save
        format.html { redirect_to ideas_path, notice: 'Memberimage was successfully created.' }
        format.json { render json: @memberimage, status: :created, location: @memberimage }
      else
        format.html { render action: "new" }
        format.json { render json: @memberimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberimages/1
  # PUT /memberimages/1.json
  def update
    @memberimage = Memberimage.find(params[:id])

    respond_to do |format|
      if @memberimage.update_attributes(params[:memberimage])
        format.html { redirect_to ideas_path, notice: 'Memberimage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @memberimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberimages/1
  # DELETE /memberimages/1.json
  def destroy
    @memberimage = Memberimage.find(params[:id])
    @memberimage.destroy

    respond_to do |format|
      format.html { redirect_to memberimages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memberimages_helper.rb
module MemberimagesHelper
end

app/views/memberimages/_form.html.erb
<%= form_for(@memberimage) do |f| %>
  <% if @memberimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memberimage.errors.count, "error") %> prohibited this memberimage from being saved:</h2>

      <ul>
      <% @memberimage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Choose_image %>
    <%= f.file_field :image %>
  </div>
  <br/>
  <div class="field">
    
    <%= f.hidden_field :member_id, :value => current_member.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberimages/edit.html.erb
<% provide(:title, 'Edit my photo') %>
<div class="hero-unit"><h1>Want to Edit your image?</h1></div>
<div class="container">
<%= render 'form' %>
</div>
<%= link_to 'Show', @memberimage %><% if member_signed_in? %>
<% if current_member.email == "kantaharikrishna@gmail.com" %> |
<%= link_to 'Back', memberimages_path %>
<% end %>
<% end %>

app/views/memberimages/index.html.erb
<h1>Listing memberimages</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Member</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberimages.each do |memberimage| %>
  <tr>
    <td><%= memberimage.image %></td>
    <td><%= memberimage.member_id %></td>
    <td><%= link_to 'Show', memberimage %></td>
    <td><%= link_to 'Edit', edit_memberimage_path(memberimage) %></td>
    <td><%= link_to 'Destroy', memberimage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memberimage', new_memberimage_path %>

app/views/memberimages/new.html.erb
<div class="hero-unit"<h1>Upload your image</h1></div>

<%= render 'form' %>

<%= link_to 'Back', memberimages_path %>

app/views/memberimages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= image_tag(@memberimage.image_url, :width => 600) if @memberimage.image.present? %>
</p>

<p>
  <b>Member:</b>
  <%= @memberimage.member_id %>
</p>


<%= link_to 'Edit', edit_memberimage_path(@memberimage) %> <% if member_signed_in? %>
<% if current_member.email == "kantaharikrishna@gmail.com" %>|
<%= link_to 'Back', memberimages_path %>
<% end %>
<% end %>