config/routes.rb
Railsgirls1::Application.routes.draw do

  

  

  resources :quotes

  resources :memberimages

	devise_for :members,:controllers => { :registrations =>'registration'}
	match 'dashboard' => 'home#dashboard'

	resources :comments

	root :to => redirect('/ideas')

	resources :ideas
	match '/contact', :to => 'static#contact'
	match '/technonews', :to => 'static#techno_news'
	match '/socialnews', :to => 'static#social_news'
	match '/kushii', :to => 'static#kushi'
	match '/profile', :to => 'static#profile'
	match '/memberslist', :to => 'static#memberslist'
  match '/details' => 'static#details'
	
	get 'ideas/poll'
	post 'ideas/poll'
	resources :kushis

end

app/models/kushi.rb
class Kushi < ActiveRecord::Base
  attr_accessible :kushi_image
   mount_uploader :kushi_image, KushiImageUploader
end

app/controllers/kushis_controller.rb
class KushisController < ApplicationController
before_filter :admin_check, :only => ["index","edit","update","destroy","create","new"]
  # GET /kushis
  # GET /kushis.json
  def index
    @kushis = Kushi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kushis }
    end
  end

  # GET /kushis/1
  # GET /kushis/1.json
  def show
    @kushi = Kushi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kushi }
    end
  end

  # GET /kushis/new
  # GET /kushis/new.json
  def new
    @kushi = Kushi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kushi }
    end
  end

  # GET /kushis/1/edit
  def edit
    @kushi = Kushi.find(params[:id])
  end

  # POST /kushis
  # POST /kushis.json
  def create
    @kushi = Kushi.new(params[:kushi])

    respond_to do |format|
      if @kushi.save
        format.html { redirect_to @kushi, notice: 'Kushi was successfully created.' }
        format.json { render json: @kushi, status: :created, location: @kushi }
      else
        format.html { render action: "new" }
        format.json { render json: @kushi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kushis/1
  # PUT /kushis/1.json
  def update
    @kushi = Kushi.find(params[:id])

    respond_to do |format|
      if @kushi.update_attributes(params[:kushi])
        format.html { redirect_to @kushi, notice: 'Kushi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kushi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kushis/1
  # DELETE /kushis/1.json
  def destroy
    @kushi = Kushi.find(params[:id])
    @kushi.destroy

    respond_to do |format|
      format.html { redirect_to kushis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kushis_helper.rb
module KushisHelper
end

app/views/kushis/_form.html.erb
<%= form_for @kushi, :html => {:multipart => true} do |f| %>
  <% if @kushi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kushi.errors.count, "error") %> prohibited this kushi from being saved:</h2>

      <ul>
      <% @kushi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  <p>
    <%= f.file_field :kushi_image %>
  </p>
    <%= f.submit %>
  </div>
<% end %>

app/views/kushis/edit.html.erb
<h1>Editing kushi</h1>

<%= render 'form' %>

<%= link_to 'Show', @kushi %> |
<%= link_to 'Back', kushis_path %>

app/views/kushis/index.html.erb
<h1>Listing kushis</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kushis.each do |kushi| %>
  <tr>
  <td><%= image_tag kushi.kushi_image_url.to_s %></td>
    <td><%= link_to 'Show', kushi %></td>
    <td><%= link_to 'Edit', edit_kushi_path(kushi) %></td>
    <td><%= link_to 'Destroy', kushi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kushi', new_kushi_path %>

app/views/kushis/new.html.erb
<h1>New kushi</h1>

<%= render 'form' %>

<%= link_to 'Back', kushis_path %>

app/views/kushis/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @kushi.kushi_image_url.to_s %>

<%= link_to 'Edit', edit_kushi_path(@kushi) %> |
<%= link_to 'Back', kushis_path %>